import { TeamMember, Task } from "./types";

export const sampleTasks: Task[] = [
    {
        id: "t1",
        title: "Review blood test result...",
        category: "Cardiology",
        assignedBy: "Owens/Koby",
        priority: "High",
        completed: false
    },
    {
        id: "t2",
        title: "Review blood test result...",
        category: "Cardiology",
        assignedBy: "Owens/Koby",
        priority: "Medium",
        completed: false
    },
    {
        id: "t3",
        title: "Review blood test result...",
        category: "Cardiology",
        assignedBy: "Owens/Koby",
        priority: "Low",
        completed: false
    },
    {
        id: "t4",
        title: "Review blood test result...",
        category: "Cardiology",
        assignedBy: "Owens/Koby",
        priority: "Medium",
        completed: false
    },
    {
        id: "t5",
        title: "Review blood test result...",
        category: "Cardiology",
        assignedBy: "Owens/Koby",
        priority: "Medium",
        completed: false
    },
    {
        id: "t6",
        title: "Review blood test result...",
        category: "Cardiology",
        assignedBy: "Owens/Koby",
        priority: "Medium",
        completed: false
    },
    {
        id: "t7",
        title: "Review blood test result...",
        category: "Cardiology",
        assignedBy: "Owens/Koby",
        priority: "Medium",
        completed: false
    },
    {
        id: "t8",
        title: "Review blood test result...",
        category: "Cardiology",
        assignedBy: "Owens/Koby",
        priority: "Medium",
        completed: false
    }
];

export const DUMMY_TEAM_MEMBERS: TeamMember[] = [
    {
        id: "1",
        firstName: "Cameron",
        lastName: "Williamson",
        email: "tanya.hill@example.com",
        phone: "(555) 123-4567",
        mobileNumber: "(205) 555-0100",
        pager: "P-1120",
        role: "Attending Surgeon",
        roles: ["Example Role 1", "Example Role 2", "Example Role 3"],
        department: "Surgery",
        specialty: "General Surgery",
        specialties: ["Surgery", "Neurology"],
        profession: "Doctor",
        status: "on-duty",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 25, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 2),
        tasksList: sampleTasks.slice(2, 4)
    },
    {
        id: "2",
        firstName: "Jenny",
        lastName: "Wilson",
        email: "jenny.wilson@example.com",
        phone: "(555) 234-5678",
        mobileNumber: "(205) 555-0101",
        pager: "P-1121",
        role: "Attending Surgeon",
        roles: ["Example Role 1"],
        department: "Surgery",
        specialty: "Orthopedic Surgery",
        specialties: ["Orthopedics"],
        profession: "Doctor",
        status: "on-call",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 20, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 1),
        tasksList: sampleTasks.slice(1, 2)
    },
    {
        id: "3",
        firstName: "Darrell",
        lastName: "Steward",
        email: "darrell.steward@example.com",
        phone: "(555) 345-6789",
        mobileNumber: "(205) 555-0102",
        pager: "P-1122",
        role: "Attending Surgeon",
        roles: ["Example Role 1", "Example Role 2"],
        department: "Surgery",
        specialty: "Cardiac Surgery",
        specialties: ["Cardiac Surgery"],
        profession: "Doctor",
        status: "on-or",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 15, 2026",
        accessType: "Team Admin",
        assignedTasks: sampleTasks.slice(0, 2),
        tasksList: sampleTasks.slice(2, 3)
    },
    {
        id: "4",
        firstName: "Arlene",
        lastName: "McCoy",
        email: "arlene.mccoy@example.com",
        phone: "(555) 456-7890",
        mobileNumber: "(205) 555-0103",
        pager: "P-1123",
        role: "Attending Surgeon",
        roles: ["Example Role 1"],
        department: "Surgery",
        specialty: "Neurosurgery",
        specialties: ["Neurosurgery"],
        profession: "Doctor",
        status: "day-off",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 10, 2026",
        accessType: "Member",
        assignedTasks: [],
        tasksList: sampleTasks.slice(0, 2)
    },
    {
        id: "5",
        firstName: "Savannah",
        lastName: "Nguyen",
        email: "savannah.nguyen@example.com",
        phone: "(555) 567-8901",
        mobileNumber: "(205) 555-0104",
        pager: "P-1124",
        role: "Anesthesiologist",
        roles: ["Example Role 1"],
        department: "Anesthesiology",
        specialty: "General Anesthesia",
        specialties: ["Anesthesiology"],
        profession: "Doctor",
        status: "on-call",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 18, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 1),
        tasksList: sampleTasks.slice(1, 3)
    },
    {
        id: "6",
        firstName: "Kristin",
        lastName: "Watson",
        email: "kristin.watson@example.com",
        phone: "(555) 678-9012",
        mobileNumber: "(205) 555-0105",
        pager: "P-1125",
        role: "Anesthesiologist",
        roles: ["Example Role 1"],
        department: "Anesthesiology",
        specialty: "Pediatric Anesthesia",
        specialties: ["Pediatric Anesthesia"],
        profession: "Doctor",
        status: "on-duty",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 22, 2026",
        accessType: "Member",
        assignedTasks: [],
        tasksList: sampleTasks.slice(0, 2)
    },
    {
        id: "7",
        firstName: "Cameron",
        lastName: "Williamson",
        email: "cameron.williamson2@example.com",
        phone: "(555) 789-0123",
        mobileNumber: "(205) 555-0106",
        pager: "P-1126",
        role: "Resident",
        roles: ["Example Role 1"],
        department: "Anesthesiology",
        specialty: "Critical Care",
        specialties: ["Critical Care"],
        profession: "Doctor",
        status: "day-off",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 12, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 1),
        tasksList: []
    },
    {
        id: "8",
        firstName: "Courtney",
        lastName: "Henry",
        email: "courtney.henry@example.com",
        phone: "(555) 890-1234",
        mobileNumber: "(205) 555-0107",
        pager: "P-1127",
        role: "Cardiologist",
        roles: ["Example Role 1"],
        department: "Cardiology",
        specialty: "Interventional Cardiology",
        specialties: ["Cardiology"],
        profession: "Doctor",
        status: "day-off",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 8, 2026",
        accessType: "Member",
        assignedTasks: [],
        tasksList: sampleTasks.slice(0, 2)
    },
    {
        id: "9",
        firstName: "Kathryn",
        lastName: "Murphy",
        email: "kathryn.murphy@example.com",
        phone: "(555) 901-2345",
        mobileNumber: "(205) 555-0108",
        pager: "P-1128",
        role: "Cardiologist",
        roles: ["Example Role 1"],
        department: "Cardiology",
        specialty: "Electrophysiology",
        specialties: ["Cardiology"],
        profession: "Doctor",
        status: "on-or",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 5, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 2),
        tasksList: sampleTasks.slice(2, 3)
    },
    {
        id: "10",
        firstName: "Marvin",
        lastName: "McKinney",
        email: "marvin.mckinney@example.com",
        phone: "(555) 012-3456",
        mobileNumber: "(205) 555-0109",
        pager: "P-1129",
        role: "Cardiac Surgeon",
        roles: ["Example Role 1"],
        department: "Cardiology",
        specialty: "Cardiac Surgery",
        specialties: ["Cardiac Surgery"],
        profession: "Doctor",
        status: "on-call",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 1, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 1),
        tasksList: sampleTasks.slice(1, 4)
    },
    {
        id: "11",
        firstName: "Guy",
        lastName: "Hawkins",
        email: "guy.hawkins@example.com",
        phone: "(555) 123-9876",
        mobileNumber: "(205) 555-0110",
        pager: "P-1130",
        role: "Nurse",
        roles: ["Example Role 1"],
        department: "Nursing",
        specialty: "Critical Care",
        specialties: ["Nursing"],
        profession: "Nurse",
        status: "on-or",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 16, 2026",
        accessType: "Member",
        assignedTasks: [],
        tasksList: sampleTasks.slice(0, 2)
    },
    {
        id: "12",
        firstName: "Brooklyn",
        lastName: "Simmons",
        email: "brooklyn.simmons@example.com",
        phone: "(555) 234-8765",
        mobileNumber: "(205) 555-0111",
        pager: "P-1131",
        role: "Nurse",
        roles: ["Example Role 1"],
        department: "Nursing",
        specialty: "Emergency Nursing",
        specialties: ["Nursing"],
        profession: "Nurse",
        status: "on-duty",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 14, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 2),
        tasksList: sampleTasks.slice(2, 4)
    },
    {
        id: "13",
        firstName: "Cameron",
        lastName: "Williamson",
        email: "cameron.williamson3@example.com",
        phone: "(555) 345-7654",
        mobileNumber: "(205) 555-0112",
        pager: "P-1132",
        role: "Radiologist",
        roles: ["Example Role 1"],
        department: "Radiology",
        specialty: "Diagnostic Radiology",
        specialties: ["Radiology"],
        profession: "Doctor",
        status: "on-duty",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 20, 2026",
        accessType: "Member",
        assignedTasks: [],
        tasksList: sampleTasks.slice(0, 2)
    },
    // Anesthesiology - 4th member
    {
        id: "14",
        firstName: "Leslie",
        lastName: "Alexander",
        email: "leslie.alexander@example.com",
        phone: "(555) 456-7654",
        mobileNumber: "(205) 555-0113",
        pager: "P-1133",
        role: "Anesthesiologist",
        roles: ["Example Role 1", "Example Role 2"],
        department: "Anesthesiology",
        specialty: "Obstetric Anesthesia",
        specialties: ["Obstetric Anesthesia"],
        profession: "Doctor",
        status: "on-duty",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 25, 2026",
        accessType: "Team Admin",
        assignedTasks: sampleTasks.slice(0, 2),
        tasksList: sampleTasks.slice(2, 4)
    },
    // Cardiology - 4th member
    {
        id: "15",
        firstName: "Ronald",
        lastName: "Richards",
        email: "ronald.richards@example.com",
        phone: "(555) 567-8765",
        mobileNumber: "(205) 555-0114",
        pager: "P-1134",
        role: "Cardiologist",
        roles: ["Example Role 1"],
        department: "Cardiology",
        specialty: "Heart Failure",
        specialties: ["Heart Failure"],
        profession: "Doctor",
        status: "on-call",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 18, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 1),
        tasksList: sampleTasks.slice(1, 3)
    },
    // Nursing - 3rd member
    {
        id: "16",
        firstName: "Theresa",
        lastName: "Webb",
        email: "theresa.webb@example.com",
        phone: "(555) 678-9876",
        mobileNumber: "(205) 555-0115",
        pager: "P-1135",
        role: "Nurse",
        roles: ["Example Role 1"],
        department: "Nursing",
        specialty: "Pediatric Nursing",
        specialties: ["Pediatric Nursing"],
        profession: "Nurse",
        status: "on-call",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 22, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 2),
        tasksList: sampleTasks.slice(2, 4)
    },
    // Nursing - 4th member
    {
        id: "17",
        firstName: "Albert",
        lastName: "Flores",
        email: "albert.flores@example.com",
        phone: "(555) 789-0987",
        mobileNumber: "(205) 555-0116",
        pager: "P-1136",
        role: "Nurse",
        roles: ["Example Role 1"],
        department: "Nursing",
        specialty: "ICU Nursing",
        specialties: ["ICU Nursing"],
        profession: "Nurse",
        status: "day-off",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 19, 2026",
        accessType: "Member",
        assignedTasks: [],
        tasksList: sampleTasks.slice(0, 2)
    },
    // Radiology - 2nd member
    {
        id: "18",
        firstName: "Darlene",
        lastName: "Robertson",
        email: "darlene.robertson@example.com",
        phone: "(555) 890-1098",
        mobileNumber: "(205) 555-0117",
        pager: "P-1137",
        role: "Radiologist",
        roles: ["Example Role 1"],
        department: "Radiology",
        specialty: "Interventional Radiology",
        specialties: ["Interventional Radiology"],
        profession: "Doctor",
        status: "on-or",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 15, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 1),
        tasksList: sampleTasks.slice(1, 3)
    },
    // Radiology - 3rd member
    {
        id: "19",
        firstName: "Jacob",
        lastName: "Jones",
        email: "jacob.jones@example.com",
        phone: "(555) 901-2109",
        mobileNumber: "(205) 555-0118",
        pager: "P-1138",
        role: "Radiologist",
        roles: ["Example Role 1"],
        department: "Radiology",
        specialty: "Neuroradiology",
        specialties: ["Neuroradiology"],
        profession: "Doctor",
        status: "on-call",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 10, 2026",
        accessType: "Member",
        assignedTasks: sampleTasks.slice(0, 2),
        tasksList: sampleTasks.slice(2, 4)
    },
    // Radiology - 4th member
    {
        id: "20",
        firstName: "Jane",
        lastName: "Cooper",
        email: "jane.cooper@example.com",
        phone: "(555) 012-3210",
        mobileNumber: "(205) 555-0119",
        pager: "P-1139",
        role: "Radiologist",
        roles: ["Example Role 1", "Example Role 2"],
        department: "Radiology",
        specialty: "Musculoskeletal Radiology",
        specialties: ["Musculoskeletal Radiology"],
        profession: "Doctor",
        status: "day-off",
        scheduleType: "Regular",
        scheduleDays: "Mon-Fri",
        scheduleTime: "07:00-19:00",
        tasks: 2,
        joinDate: "March 5, 2026",
        accessType: "Department Admin",
        assignedTasks: [],
        tasksList: sampleTasks.slice(0, 2)
    }
];

export const ROLES = [
    "Attending Surgeon",
    "Anesthesiologist",
    "Resident",
    "Cardiologist",
    "Cardiac Surgeon",
    "Nurse",
    "Radiologist"
];

export const PROFESSIONS = [
    "Doctor",
    "Nurse",
    "Surgeon",
    "Anesthesiologist"
];

export const DEPARTMENTS = [
    "Surgery",
    "Anesthesiology",
    "Cardiology",
    "Nursing",
    "Radiology"
];

export const SPECIALTIES = [
    "General Surgery",
    "Orthopedic Surgery",
    "Cardiac Surgery",
    "Neurosurgery",
    "General Anesthesia",
    "Pediatric Anesthesia",
    "Critical Care",
    "Interventional Cardiology",
    "Electrophysiology",
    "Emergency Nursing",
    "Diagnostic Radiology"
];

export const STATUSES = [
    { value: "on-duty", label: "On Duty", color: "emerald" },
    { value: "on-call", label: "On Call", color: "amber" },
    { value: "on-or", label: "On OR", color: "blue" },
    { value: "day-off", label: "Day Off", color: "slate" }
] as const;

export const ACCESS_TYPES = [
    { value: "Member", label: "Member" },
    { value: "Team Admin", label: "Team Admin" },
    { value: "Department Admin", label: "Department Admin" }
] as const;
